#!/usr/bin/env python
# coding=utf8

import fontforge
from argparse import ArgumentParser

# Setup and parse the comand-line arguments
parser = ArgumentParser()
parser.add_argument("--input", help="input file name")
parser.add_argument("--output", help="output file name")
args = parser.parse_args()

# Just open and save the font, to fix some internal structure
fontforge.open(args.input).generate(args.output)
