#!/usr/bin/env python
# coding=utf8

import fontforge
from argparse import ArgumentParser

# Setup and parse the comand-line arguments
parser = ArgumentParser()
parser.add_argument("--input", help="input file name")
parser.add_argument("--output", help="output file name")
parser.add_argument("--name", help="font name")
parser.add_argument("--style", help="font sub-style")
parser.add_argument("--version", help="text to add to the existing version")
args = parser.parse_args()

if args.style:
    args.style = " " + args.style
fullname = "{}{}".format(args.name, args.style)

# Open the file
delugia=fontforge.open(args.input)

# Rename the file
delugia.fontname = fullname.replace(" ", "")
delugia.familyname = args.name
delugia.fullname = fullname
delugia.appendSFNTName("English (US)", "Family", args.name)
delugia.appendSFNTName("English (US)", "Preferred Family", args.name)
delugia.appendSFNTName("English (US)", "Compatible Full", fullname)
delugia.appendSFNTName("English (US)", "UniqueID", "{}{}".format(args.name, args.style))
delugia.appendSFNTName("English (US)", "Trademark", "")

# Mix our version information in
delugia.sfntRevision = None # Auto-set (refreshed) by fontforge
delugia.appendSFNTName("English (US)", "Version", args.version)
delugia.version = args.version

# Save
delugia.generate(args.output)
print("Generated '{}' from {}{} version {}".format(args.output, args.name, args.style, args.version))
