#!/usr/bin/env python
# coding=utf8

import fontforge
from argparse import ArgumentParser

# Setup and parse the comand-line arguments
parser = ArgumentParser()
parser.add_argument("--input", help="input file name")
parser.add_argument("--output", help="output file name")
parser.add_argument("--name", help="font name")
args = parser.parse_args()

# Open the file
delugia=fontforge.open(args.input)

# Rename the file
delugia.fontname="{}-Regular".format(args.name)
delugia.familyname=args.name
delugia.fullname=args.name
delugia.appendSFNTName("English (US)", "Copyright", "Need something here")
delugia.appendSFNTName("English (US)", "UniqueID", "{} Regular".format(args.name))
delugia.appendSFNTName("English (US)", "Trademark", "")

# Save
delugia.generate(args.output)
