#!/usr/bin/env python
# coding=utf8

import fontforge
from argparse import ArgumentParser

# Setup and parse the comand-line arguments
parser = ArgumentParser()
parser.add_argument("--input", help="input file name")
parser.add_argument("--output", help="output file name")
parser.add_argument("--name", help="font name")
parser.add_argument("--version", help="(optional) text to add to the existing version")
args = parser.parse_args()

# Open the file
delugia=fontforge.open(args.input)

# Rename the file
delugia.fontname="{}-Regular".format(args.name).replace(" ", "")
delugia.familyname=args.name
delugia.fullname=args.name
delugia.appendSFNTName("English (US)", "Preferred Family", args.name)
delugia.appendSFNTName("English (US)", "Compatible Full", args.name)
delugia.appendSFNTName("English (US)", "UniqueID", "{} Regular".format(args.name))
delugia.appendSFNTName("English (US)", "Trademark", "")

# The grave accent type is somehow not correctly detected;
# we want it to be an ordinary character
delugia["grave"].glyphclass="baseglyph"

# Mix our version information in
if (args.version):
    enriched_version = "{}/{}".format(delugia.version, args.version)
    delugia.appendSFNTName("English (US)", "Version", enriched_version)
    delugia.version = enriched_version
    print("Set new font version {}".format(delugia.version));

# Save
delugia.generate(args.output)
